# Generated by Django 3.1.4 on 2020-12-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyParty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_song_id', models.CharField(max_length=50)),
                ('song_name', models.CharField(max_length=150)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_length', models.IntegerField()),
                ('is_playing', models.BooleanField(default=False)),
                ('is_votable', models.BooleanField(default=False)),
                ('song_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(default=False)),
                ('party_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyParty.partysession')),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinedPartySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_session_host', models.BooleanField(default=False)),
                ('party_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyParty.partysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_vote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotifyParty.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='user_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyParty.userplaylist'),
        ),
    ]
